### ISSUE TITLE
lvs issue with openlane based notebooks

### ISSUE THREAD

**Issue by proppy** [chipsalliance/silicon-notebooks#66]
openlane based notebooks like https://github.com/chipsalliance/silicon-notebooks/blob/main/xls-adder-openlane.ipynb seems to be failing LVS with the following error:
```
Cannot find cell __adder__adder in file /content/runs/RUN_2023.04.27_16.16.28/results/signoff/__adder__adder.spice
Traceback (most recent call last):
  File "/content/conda-env/share/openlane/scripts/count_lvs.py", line 118, in <module>
    failures = count_LVS_failures(args.file)
  File "/content/conda-env/share/openlane/scripts/count_lvs.py", line 36, in count_LVS_failures
    with open(filename, "r") as cfile:
FileNotFoundError: [Errno 2] No such file or directory: '/content/runs/RUN_2023.04.27_16.16.28/logs/signoff/36-__adder__adder.lef.lvs.json'
[ERROR]: Step(36:lvs) failed with error:
-code 1 -level 0 -errorstack {INNER {invokeStk1 exec python3 /content/conda-env/share/openlane/scripts/count_lvs.py -f /content/runs/RUN_2023.04.27_16.16.28/logs/signoff/36-__adder__adder.lef.lvs.json |& tee >&@stdout /content/runs/RUN_2023.04.27_16.16.28/reports/signoff/36-__adder__adder.lvs.rpt} CALL run_lvs CALL run_lvs_step CALL {run_non_interactive_mode -verbose 99 -design .}} -errorcode {CHILDSTATUS 12315 1} -errorinfo {child process exited abnormally
    while executing
"exec python3 $::env(SCRIPTS_DIR)/count_lvs.py  -f $extraction_prefix.json  |& tee $::env(TERMINAL_OUTPUT) $count_lvs_rpt"
    (procedure "run_lvs" line 70)
    invoked from within
"run_lvs"
    (procedure "run_lvs_step" line 10)
    invoked from within
"run_lvs_step"} -errorline 1
```
Looking at the extracted spice netlist it seems that the top level `subckt` is named:
```
.subckt x__adder__adder VGND VPWR in1 in2 out[0] out[1]
```
instead of:
```
.subckt __adder__adder VGND VPWR in1 in2 out[0] out[1]
```

I suspect this might be fixed with a newer magic version, but we need to fix https://github.com/hdl/conda-eda/issues/324 and https://github.com/hdl/conda-eda/issues/325 to get a newer build.

**Comment by proppy** [comment]
In the meantime it might better to disable `LVS`.
